package ast.declaraciones;

public enum TipoDescrT {
	DEC_TIPO, DECLARACION_INT, DECLARACION_REAL, DECLARACION_ARRAY,
	DECLARACION_REGISTRO, DECLARACION_PUNTERO, DECLARACION_OBJETO,
	DECLARACION_OBJETO_SIMPLE, DESCRIPCION_TIPO;
}
