package ast.expresiones;

public enum TipoE {
	MENOR, MAYOR, MAYOR_IGUAL, MENOR_IGUAL, IGUAL, DISTINTO,
	OR, SUMA, RESTA, MUL, DIV, MOD, AND, NOT, MENOS, CAST_INT,
	CAST_REAL, NULL, DESIGNADOR, EXPRESION_FUNCION, EXPRESION_METODO,
	ENTERO, REAL, ID;
}
